### ISSUE TITLE
Latest hardware version possible compatibility issue

### ISSUE THREAD

**Issue by ncoop23** [furrtek/portapack-havoc#75] opened 2017-07-24 01:19 UTC
There are changes in the latest hardware revision of the PortaPack which require a firmware update to allow the device to work.  The code is not commented enough for me to understand what exactly is going on or else I would take a crack at fixing it.  I'm afraid of bricking my PortaPack by flashing the current Havoc firmware.

**Comment by ncoop23** [comment] 2017-07-24 01:29
It looks like they changed the LCD on the new hardware or at least how the backlight works.

**Comment by jboone** [comment] 2017-07-24 03:06
I'm traveling at the moment, but was hoping to take a crack at merging the necessary changes, since I'm the party responsible for the hardware changes... ;-)

@ncoop23, do you already have a revision 20170522 board in your hands?

        - Jared

**Comment by ncoop23** [comment] 2017-07-24 03:30
I have one of the boards and can test on it.  I'm afraid to flash the new firmware for fear of bricking it since I don't really know what got changed.

**Comment by jboone** [comment] 2017-07-24 03:51
Holy smokes, looks like Furrtek already merged all the changes! I'll verify on my new and old hardware and share my results shortly.

        - Jared

**Comment by jboone** [comment] 2017-07-24 05:07
Furrtek doesn't have the newest changes incorporated, but was up to date a month ago. That's recent enough that HAVOC should run on the new hardware. I checked it out, and while there might be a bit of breakage, there's no harm in running the latest code compiled from source on your 20170522 PortaPack. I will look into merging the newest changes from my repository, they *should* be fairly simple.

**Comment by ImDroided** [comment] 2017-07-24 05:11
I can confirm the firmware works. I have the latest board. Some stuff is having issues it seems but most seems to work.

**Comment by gh0stshell** [comment] 2017-07-24 05:14
Do we have to upgrade boards to keep using Havoc?

**Comment by jboone** [comment] 2017-07-24 05:39
@gh0stshell Nope, software merged from sharebrained/portapack-hackrf will detect the board revision (by seeing which audio codec is on the I2C bus) and load the correct drivers and CPLD code. So old PortaPacks will continue to work with HAVOC. However, I need to send Furrtek a new PortaPack board...

**Comment by jboone** [comment] 2017-07-24 05:41
@ImDroided Your #76 mic issue is probably caused by the HAVOC repo being a bit behind. I fixed some mic configuration stuff for the new hardware revision in the last month's commits. However, even after the merge with the latest code, there may still be issues that need to be resolved. We'll check it out.

**Comment by Redouan29** [comment] 2017-07-24 06:16
So the new hardware revision of portapack works fine and is safe to use havoc addon? Or should we wait?

**Comment by furrtek** [comment] 2017-07-24 12:27
I'll sync HAVOC today with @jboone latest code. I saw some new files related to the new audio codec and LCD I/O but you'll have to test it yourself since I have the 1st board version.
I'll try to make sure the fw always on both versions :)

**Comment by Redouan29** [comment] 2017-07-24 13:12
@furrtek & @jboone thanks!

**Comment by ImDroided** [comment] 2017-07-25 02:44
Ok so I just compiled and flashed your most recent changes and its still a no go on the mic. LCD seems to work a little better.

**Comment by ImDroided** [comment] 2017-07-30 21:13
Mic is now working just fine LCD seems to perform better on my end also.

**Closed** 2017-07-30 23:24 UTC

**Comment by jashsu** [comment] 2017-08-01 06:37
Will a prebuilt binary release be uploaded?
