### ISSUE TITLE
Morse TX transmit only lines

### ISSUE THREAD

**Issue by Giorgiofox** [furrtek/portapack-havoc#27] opened 2017-02-16 22:00 UTC
Hello, 
I'm Trying MORSE TX under "Code Trasmitter":
In FM mode it work well, transmitting dot and lines as message set, but it not work using CW mode:
it transmit only lines, or only elements of equal length:

![cwportapack](https://cloud.githubusercontent.com/assets/1769743/23043235/eeb73e20-f49b-11e6-9e84-9ef4609cf28c.PNG)

_(the image is the transmission of "PORTAPACK" word_
 
In FM mode is impossible to stop trasmission (the stop key turn green, but transmission continue)

**Comment by furrtek** [comment] 2017-03-03 07:12
Both issues should be fixed in 09611ba

Wrong CW transmission was caused by a variable mixup.
FM transmit not stopping + crash was caused by asking an inexistent thread to terminate.

**Closed by furrtek** 2017-03-03 07:12 UTC
Labels: bug
