### ISSUE TITLE
Flex pager support

### ISSUE THREAD

**Issue by ImDroided** [furrtek/portapack-havoc#149] opened 2018-01-07 07:39 UTC
In the pager section is there a way Flex could be added? In the Chicago area Flex is used. Would be cool to decode these.

Found this program 

https://github.com/Discriminator/PDW

https://en.wikipedia.org/wiki/FLEX_(protocol)

**Comment by furrtek** [comment] 2018-01-07 19:13
Duplicate of #130

**Closed by furrtek** 2018-01-07 19:13 UTC

**Comment by ImDroided** [comment] 2018-01-07 19:24
Sorry didnt see that one.
