### ISSUE TITLE
Freeze during soundboard exit

### ISSUE THREAD

**Issue by goldcove** [furrtek/portapack-havoc#2] opened 2016-09-19 08:11 UTC
The firmware freezes when you try to exit the soundboard. 
Rev 67a3b02

**Comment by furrtek** [comment] 2016-09-23 10:22
Can't reproduce. Maybe RAM init issue, looking into it. Thanks.

**Comment by Pine-d-Huitre** [comment] 2016-09-25 12:20
Pour reproduire le bug il faut : 
- entrer dans le TEDI/LCR
- retourner au menu principal
- entrer dans le soundboard
- retourner au menu principal
- entrer dans le TEDI/LCR
- retourner au menu principal
- entrer dans le soundboard
et là, en voulant sortir du soundboard ça freeze

**Comment by furrtek** [comment] 2016-09-27 01:03
Still can't reproduce, guessing it's either RAM init (couldn't find anything for now) or something to do with the number of wav files found for the soundboard.

**Comment by Pine-d-Huitre** [comment] 2016-09-27 20:57
Indeed, I can't reproduce it anymore.

**Comment by furrtek** [comment] 2016-12-26 12:52
Closing as couldn't reproduce even after RAM clear. Also changed stuff in RAM init and files checking which may have fixed the initial problem.

**Closed by furrtek** 2016-12-26 12:52 UTC
